name: "Pipeline"

on:
  push:
    branches: 
      - main

jobs:
  job-main:
    name: main
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install InvokeBuild
        run: |
          Write-Output "Installing InvokeBuild"
          Install-Module -Name InvokeBuild -Scope "CurrentUser" -Force -ErrorAction "Stop"

      - name: build
        run: |
          Invoke-Build -Task Build

      - name: Analyze
        run: |
          Invoke-Build -Task Analyze

      - name: Test
        run: |
          Invoke-Build -Task Test
